### ISSUE TITLE
[Bug] login issue 0.2.1 (120)

### ISSUE THREAD

**Issue by georgepstaylor** [sorenmortensen/symonds-timetable#9]
Logging in results in a 404
http://i.imgur.com/g8YaxCg.jpg

**Comment by sorenmortensen** [comment]
I've identified the cause - this is due to the authentication keys not being under version control

**Comment by sorenmortensen** [comment]
Not yet fixed - 0.2.1 (141) is able to log in but not retrieve timetable information.

**Comment by sorenmortensen** [comment]
Not going to continue to attempt to fix this, as it's caused by using Travis for continuous delivery, and that feature isn't needed.
